### ISSUE TITLE
App freezes on certain devices

### ISSUE THREAD

**Issue by AdityaMitra5102** [Android-Club-VITAP/VTOP-Extended#7]
I tested this app on Galaxy M30s. I just opened the app and opened the quiz section then I turned the phone horizontally then my phone got hang then I force to restart my phone. I have uploaded a video you can check here - https://drive.google.com/file/d/1sKD5laMOnh5Ih3H2tgwPWyGLfKVW2w-T/view?usp=sharing

- baswaraj.20bcd7113@vitap.ac.in

**Comment by amritesh-dasari** [comment]
We tried reproducing this issue and couldn't do so, nonetheless, we'll look at making changes to the inapp_webview to make it a smoother experience.
