### ISSUE TITLE
Feature Suggest: Parent Login

### ISSUE THREAD

**Issue by AdityaMitra5102** [Android-Club-VITAP/VTOP-Extended#8]
While logging in you may add features for parent login and display the relevant content in their account. (Like the things going in the campus and all.)

 -mithun.20bci7134@vitap.ac.in

**Comment by amritesh-dasari** [comment]
The originally intended userbase for this app was supposed to be students only. For now, we are working on improving the user experience and squashing bugs. Maybe we'll implement a parent login feature in the future.
