### ISSUE TITLE
Abrupt exit from app

### ISSUE THREAD

**Issue by AdityaMitra5102** [Android-Club-VITAP/VTOP-Extended#9]
If we open any feature that is mentioned under the burger icon and then press the back key, we get a very abrupt exit from the app. On pressing the back key, it should direct to the main page that we see when we log in. However, the app should exit immediately if we are currently on a page accessed from the tab bar (if it gets added) at the bottom.

-shreya.20bci7293@vitap.ac.in

**Comment by amritesh-dasari** [comment]
Thank you for letting us know, we are working on a fix.

**Comment by Somsubro-Banerjee** [comment]
This issue is fixed and will be out on next patch update :)
